// log_analyzer.hpp
// -----------------
// Parses Sentinel's JSON-lines violation logs and produces a risk-scored
// summary report. Deliberately dependency-free (no nlohmann/json etc.):
// our log format is a small, fixed, single-level JSON object per line,
// generated by our own C code, so a hand-written parser tailored to that
// exact shape is simpler and easier to audit than pulling in a general
// JSON library for one use case. If you extend the log schema to
// anything nested, switch to a real JSON library instead of extending
// this parser.
#ifndef SENTINEL_LOG_ANALYZER_HPP
#define SENTINEL_LOG_ANALYZER_HPP

#include <string>
#include <vector>
#include <map>
#include <cstdint>

namespace sentinel {

struct Violation {
    long long ts = 0;
    long long pid = 0;
    int syscall_nr = 0;
    std::string syscall_name;
    std::string policy;
};

enum class Severity { Low, Medium, High };

struct SyscallStat {
    std::string name;
    int count = 0;
    Severity severity = Severity::Low;
};

struct Report {
    int total_violations = 0;
    int distinct_syscalls = 0;
    int distinct_pids = 0;
    std::vector<SyscallStat> top_syscalls; // sorted by count, descending
    std::vector<std::string> high_severity_findings; // human-readable notes
};

// Parses every well-formed line in `path` as a Violation. Malformed
// lines are skipped (not fatal) so a half-written log line from a
// process that got SIGKILLed mid-write doesn't take down the analyzer.
std::vector<Violation> load_violations(const std::string &path);

// Turns a flat list of violations into an aggregated, severity-annotated
// report.
Report analyze(const std::vector<Violation> &violations);

// Renders `report` as a human-readable Markdown document (the same
// format used for the screenshots/tables in this project's README).
std::string render_markdown(const Report &report);

} // namespace sentinel

#endif
